/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

import pavisol.VentanaPrincipal;

/**
 *
 * @author Pedro
 */
public class PanelPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelPrincipal() {
        initComponents();
        buttonGroup1.add(agregarPedido);
        buttonGroup1.add(reabastecerStock);
        buttonGroup1.add(cobrarPedido);
        buttonGroup1.add(entregarPedido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        agregarPedido = new javax.swing.JRadioButton();
        entregarPedido = new javax.swing.JRadioButton();
        cobrarPedido = new javax.swing.JRadioButton();
        reabastecerStock = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(274, 490));
        setMinimumSize(new java.awt.Dimension(274, 490));
        setName(""); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        jPanel1.setBackground(new java.awt.Color(30, 114, 141));
        jPanel1.setMaximumSize(new java.awt.Dimension(274, 490));
        jPanel1.setMinimumSize(new java.awt.Dimension(274, 490));
        jPanel1.setPreferredSize(new java.awt.Dimension(274, 490));

        agregarPedido.setBackground(new java.awt.Color(30, 114, 141));
        agregarPedido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        agregarPedido.setForeground(new java.awt.Color(255, 255, 255));
        agregarPedido.setText("Agregar Pedido");
        agregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPedidoActionPerformed(evt);
            }
        });

        entregarPedido.setBackground(new java.awt.Color(30, 114, 141));
        entregarPedido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        entregarPedido.setForeground(new java.awt.Color(255, 255, 255));
        entregarPedido.setText("Entregar Pedido");
        entregarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarPedidoActionPerformed(evt);
            }
        });

        cobrarPedido.setBackground(new java.awt.Color(30, 114, 141));
        cobrarPedido.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cobrarPedido.setForeground(new java.awt.Color(255, 255, 255));
        cobrarPedido.setText("Cobrar Pedido");
        cobrarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobrarPedidoActionPerformed(evt);
            }
        });

        reabastecerStock.setBackground(new java.awt.Color(30, 114, 141));
        reabastecerStock.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        reabastecerStock.setForeground(new java.awt.Color(255, 255, 255));
        reabastecerStock.setText("Reabastecer Stock");
        reabastecerStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reabastecerStockActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reabastecerStock)
                    .addComponent(cobrarPedido)
                    .addComponent(agregarPedido)
                    .addComponent(entregarPedido))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(agregarPedido)
                .addGap(41, 41, 41)
                .addComponent(entregarPedido)
                .addGap(46, 46, 46)
                .addComponent(cobrarPedido)
                .addGap(33, 33, 33)
                .addComponent(reabastecerStock)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(30, 114, 141));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menú Principal");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPedidoActionPerformed
        // TODO add your handling code here:
        if(agregarPedido.isSelected() == true){
            jLabel2.setText("Agregar Pedido");
            AgregarPedido panelAgregarPedido = new AgregarPedido();
            jPanel2.add(panelAgregarPedido);
            jPanel2.revalidate();
            jPanel2.repaint();
            //VentanaPrincipal v = (VentanaPrincipal)this.getParent().getParent().getParent().getParent();
        }
    }//GEN-LAST:event_agregarPedidoActionPerformed

    private void entregarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarPedidoActionPerformed
        // TODO add your handling code here:
        if(entregarPedido.isSelected() == true){
            jLabel2.setText("Pedidos Activos");
        }
    }//GEN-LAST:event_entregarPedidoActionPerformed

    private void cobrarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobrarPedidoActionPerformed
        // TODO add your handling code here:
        if(cobrarPedido.isSelected() == true){
            jLabel2.setText("Cobrar pedidos");
        }
    }//GEN-LAST:event_cobrarPedidoActionPerformed

    private void reabastecerStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reabastecerStockActionPerformed
        // TODO add your handling code here:
        if(reabastecerStock.isSelected() == true){
            jLabel2.setText("Reabastecer stock");
        }
    }//GEN-LAST:event_reabastecerStockActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agregarPedido;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton cobrarPedido;
    private javax.swing.JRadioButton entregarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton reabastecerStock;
    // End of variables declaration//GEN-END:variables
}
